/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated.students'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedPredictRouteImport } from './routes/_authenticated.predict'
import { Route as AuthenticatedInterventionsRouteImport } from './routes/_authenticated.interventions'
import { Route as AuthenticatedFeaturesRouteImport } from './routes/_authenticated.features'
import { Route as AuthenticatedEdaRouteImport } from './routes/_authenticated.eda'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated.alerts'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated.students.$studentId'
import { Route as AuthenticatedPredictBatchRouteImport } from './routes/_authenticated.predict.batch'
import { Route as AuthenticatedModelTrainRouteImport } from './routes/_authenticated.model.train'
import { Route as AuthenticatedModelEvaluateRouteImport } from './routes/_authenticated.model.evaluate'
import { Route as AuthenticatedDataUploadRouteImport } from './routes/_authenticated.data.upload'
import { Route as AuthenticatedDataCleanRouteImport } from './routes/_authenticated.data.clean'
import { Route as AuthenticatedAdminModelsRouteImport } from './routes/_authenticated.admin.models'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPredictRoute = AuthenticatedPredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInterventionsRoute =
  AuthenticatedInterventionsRouteImport.update({
    id: '/interventions',
    path: '/interventions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeaturesRoute = AuthenticatedFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEdaRoute = AuthenticatedEdaRouteImport.update({
  id: '/eda',
  path: '/eda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedPredictBatchRoute =
  AuthenticatedPredictBatchRouteImport.update({
    id: '/batch',
    path: '/batch',
    getParentRoute: () => AuthenticatedPredictRoute,
  } as any)
const AuthenticatedModelTrainRoute = AuthenticatedModelTrainRouteImport.update({
  id: '/model/train',
  path: '/model/train',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModelEvaluateRoute =
  AuthenticatedModelEvaluateRouteImport.update({
    id: '/model/evaluate',
    path: '/model/evaluate',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataUploadRoute = AuthenticatedDataUploadRouteImport.update({
  id: '/data/upload',
  path: '/data/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDataCleanRoute = AuthenticatedDataCleanRouteImport.update({
  id: '/data/clean',
  path: '/data/clean',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminModelsRoute =
  AuthenticatedAdminModelsRouteImport.update({
    id: '/admin/models',
    path: '/admin/models',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eda': typeof AuthenticatedEdaRoute
  '/features': typeof AuthenticatedFeaturesRoute
  '/interventions': typeof AuthenticatedInterventionsRoute
  '/predict': typeof AuthenticatedPredictRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/admin/models': typeof AuthenticatedAdminModelsRoute
  '/data/clean': typeof AuthenticatedDataCleanRoute
  '/data/upload': typeof AuthenticatedDataUploadRoute
  '/model/evaluate': typeof AuthenticatedModelEvaluateRoute
  '/model/train': typeof AuthenticatedModelTrainRoute
  '/predict/batch': typeof AuthenticatedPredictBatchRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eda': typeof AuthenticatedEdaRoute
  '/features': typeof AuthenticatedFeaturesRoute
  '/interventions': typeof AuthenticatedInterventionsRoute
  '/predict': typeof AuthenticatedPredictRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/admin/models': typeof AuthenticatedAdminModelsRoute
  '/data/clean': typeof AuthenticatedDataCleanRoute
  '/data/upload': typeof AuthenticatedDataUploadRoute
  '/model/evaluate': typeof AuthenticatedModelEvaluateRoute
  '/model/train': typeof AuthenticatedModelTrainRoute
  '/predict/batch': typeof AuthenticatedPredictBatchRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/eda': typeof AuthenticatedEdaRoute
  '/_authenticated/features': typeof AuthenticatedFeaturesRoute
  '/_authenticated/interventions': typeof AuthenticatedInterventionsRoute
  '/_authenticated/predict': typeof AuthenticatedPredictRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/admin/models': typeof AuthenticatedAdminModelsRoute
  '/_authenticated/data/clean': typeof AuthenticatedDataCleanRoute
  '/_authenticated/data/upload': typeof AuthenticatedDataUploadRoute
  '/_authenticated/model/evaluate': typeof AuthenticatedModelEvaluateRoute
  '/_authenticated/model/train': typeof AuthenticatedModelTrainRoute
  '/_authenticated/predict/batch': typeof AuthenticatedPredictBatchRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alerts'
    | '/dashboard'
    | '/eda'
    | '/features'
    | '/interventions'
    | '/predict'
    | '/reports'
    | '/students'
    | '/admin/models'
    | '/data/clean'
    | '/data/upload'
    | '/model/evaluate'
    | '/model/train'
    | '/predict/batch'
    | '/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alerts'
    | '/dashboard'
    | '/eda'
    | '/features'
    | '/interventions'
    | '/predict'
    | '/reports'
    | '/students'
    | '/admin/models'
    | '/data/clean'
    | '/data/upload'
    | '/model/evaluate'
    | '/model/train'
    | '/predict/batch'
    | '/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alerts'
    | '/_authenticated/dashboard'
    | '/_authenticated/eda'
    | '/_authenticated/features'
    | '/_authenticated/interventions'
    | '/_authenticated/predict'
    | '/_authenticated/reports'
    | '/_authenticated/students'
    | '/_authenticated/admin/models'
    | '/_authenticated/data/clean'
    | '/_authenticated/data/upload'
    | '/_authenticated/model/evaluate'
    | '/_authenticated/model/train'
    | '/_authenticated/predict/batch'
    | '/_authenticated/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/predict': {
      id: '/_authenticated/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof AuthenticatedPredictRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interventions': {
      id: '/_authenticated/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof AuthenticatedInterventionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/features': {
      id: '/_authenticated/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof AuthenticatedFeaturesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eda': {
      id: '/_authenticated/eda'
      path: '/eda'
      fullPath: '/eda'
      preLoaderRoute: typeof AuthenticatedEdaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/predict/batch': {
      id: '/_authenticated/predict/batch'
      path: '/batch'
      fullPath: '/predict/batch'
      preLoaderRoute: typeof AuthenticatedPredictBatchRouteImport
      parentRoute: typeof AuthenticatedPredictRoute
    }
    '/_authenticated/model/train': {
      id: '/_authenticated/model/train'
      path: '/model/train'
      fullPath: '/model/train'
      preLoaderRoute: typeof AuthenticatedModelTrainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/model/evaluate': {
      id: '/_authenticated/model/evaluate'
      path: '/model/evaluate'
      fullPath: '/model/evaluate'
      preLoaderRoute: typeof AuthenticatedModelEvaluateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/upload': {
      id: '/_authenticated/data/upload'
      path: '/data/upload'
      fullPath: '/data/upload'
      preLoaderRoute: typeof AuthenticatedDataUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/clean': {
      id: '/_authenticated/data/clean'
      path: '/data/clean'
      fullPath: '/data/clean'
      preLoaderRoute: typeof AuthenticatedDataCleanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/models': {
      id: '/_authenticated/admin/models'
      path: '/admin/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AuthenticatedAdminModelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedPredictRouteChildren {
  AuthenticatedPredictBatchRoute: typeof AuthenticatedPredictBatchRoute
}

const AuthenticatedPredictRouteChildren: AuthenticatedPredictRouteChildren = {
  AuthenticatedPredictBatchRoute: AuthenticatedPredictBatchRoute,
}

const AuthenticatedPredictRouteWithChildren =
  AuthenticatedPredictRoute._addFileChildren(AuthenticatedPredictRouteChildren)

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEdaRoute: typeof AuthenticatedEdaRoute
  AuthenticatedFeaturesRoute: typeof AuthenticatedFeaturesRoute
  AuthenticatedInterventionsRoute: typeof AuthenticatedInterventionsRoute
  AuthenticatedPredictRoute: typeof AuthenticatedPredictRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedAdminModelsRoute: typeof AuthenticatedAdminModelsRoute
  AuthenticatedDataCleanRoute: typeof AuthenticatedDataCleanRoute
  AuthenticatedDataUploadRoute: typeof AuthenticatedDataUploadRoute
  AuthenticatedModelEvaluateRoute: typeof AuthenticatedModelEvaluateRoute
  AuthenticatedModelTrainRoute: typeof AuthenticatedModelTrainRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEdaRoute: AuthenticatedEdaRoute,
  AuthenticatedFeaturesRoute: AuthenticatedFeaturesRoute,
  AuthenticatedInterventionsRoute: AuthenticatedInterventionsRoute,
  AuthenticatedPredictRoute: AuthenticatedPredictRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedAdminModelsRoute: AuthenticatedAdminModelsRoute,
  AuthenticatedDataCleanRoute: AuthenticatedDataCleanRoute,
  AuthenticatedDataUploadRoute: AuthenticatedDataUploadRoute,
  AuthenticatedModelEvaluateRoute: AuthenticatedModelEvaluateRoute,
  AuthenticatedModelTrainRoute: AuthenticatedModelTrainRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
