/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PredictRouteImport } from './routes/predict'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as EdaRouteImport } from './routes/eda'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as PredictBatchRouteImport } from './routes/predict.batch'
import { Route as ModelTrainRouteImport } from './routes/model.train'
import { Route as ModelEvaluateRouteImport } from './routes/model.evaluate'
import { Route as DataUploadRouteImport } from './routes/data.upload'
import { Route as DataCleanRouteImport } from './routes/data.clean'
import { Route as AdminModelsRouteImport } from './routes/admin.models'

const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictRoute = PredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EdaRoute = EdaRouteImport.update({
  id: '/eda',
  path: '/eda',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => StudentsRoute,
} as any)
const PredictBatchRoute = PredictBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => PredictRoute,
} as any)
const ModelTrainRoute = ModelTrainRouteImport.update({
  id: '/model/train',
  path: '/model/train',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelEvaluateRoute = ModelEvaluateRouteImport.update({
  id: '/model/evaluate',
  path: '/model/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const DataUploadRoute = DataUploadRouteImport.update({
  id: '/data/upload',
  path: '/data/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCleanRoute = DataCleanRouteImport.update({
  id: '/data/clean',
  path: '/data/clean',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/admin/models',
  path: '/admin/models',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/eda': typeof EdaRoute
  '/features': typeof FeaturesRoute
  '/predict': typeof PredictRouteWithChildren
  '/reports': typeof ReportsRoute
  '/students': typeof StudentsRouteWithChildren
  '/admin/models': typeof AdminModelsRoute
  '/data/clean': typeof DataCleanRoute
  '/data/upload': typeof DataUploadRoute
  '/model/evaluate': typeof ModelEvaluateRoute
  '/model/train': typeof ModelTrainRoute
  '/predict/batch': typeof PredictBatchRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/eda': typeof EdaRoute
  '/features': typeof FeaturesRoute
  '/predict': typeof PredictRouteWithChildren
  '/reports': typeof ReportsRoute
  '/students': typeof StudentsRouteWithChildren
  '/admin/models': typeof AdminModelsRoute
  '/data/clean': typeof DataCleanRoute
  '/data/upload': typeof DataUploadRoute
  '/model/evaluate': typeof ModelEvaluateRoute
  '/model/train': typeof ModelTrainRoute
  '/predict/batch': typeof PredictBatchRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/eda': typeof EdaRoute
  '/features': typeof FeaturesRoute
  '/predict': typeof PredictRouteWithChildren
  '/reports': typeof ReportsRoute
  '/students': typeof StudentsRouteWithChildren
  '/admin/models': typeof AdminModelsRoute
  '/data/clean': typeof DataCleanRoute
  '/data/upload': typeof DataUploadRoute
  '/model/evaluate': typeof ModelEvaluateRoute
  '/model/train': typeof ModelTrainRoute
  '/predict/batch': typeof PredictBatchRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/eda'
    | '/features'
    | '/predict'
    | '/reports'
    | '/students'
    | '/admin/models'
    | '/data/clean'
    | '/data/upload'
    | '/model/evaluate'
    | '/model/train'
    | '/predict/batch'
    | '/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/eda'
    | '/features'
    | '/predict'
    | '/reports'
    | '/students'
    | '/admin/models'
    | '/data/clean'
    | '/data/upload'
    | '/model/evaluate'
    | '/model/train'
    | '/predict/batch'
    | '/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/eda'
    | '/features'
    | '/predict'
    | '/reports'
    | '/students'
    | '/admin/models'
    | '/data/clean'
    | '/data/upload'
    | '/model/evaluate'
    | '/model/train'
    | '/predict/batch'
    | '/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EdaRoute: typeof EdaRoute
  FeaturesRoute: typeof FeaturesRoute
  PredictRoute: typeof PredictRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  AdminModelsRoute: typeof AdminModelsRoute
  DataCleanRoute: typeof DataCleanRoute
  DataUploadRoute: typeof DataUploadRoute
  ModelEvaluateRoute: typeof ModelEvaluateRoute
  ModelTrainRoute: typeof ModelTrainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict': {
      id: '/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof PredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eda': {
      id: '/eda'
      path: '/eda'
      fullPath: '/eda'
      preLoaderRoute: typeof EdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/predict/batch': {
      id: '/predict/batch'
      path: '/batch'
      fullPath: '/predict/batch'
      preLoaderRoute: typeof PredictBatchRouteImport
      parentRoute: typeof PredictRoute
    }
    '/model/train': {
      id: '/model/train'
      path: '/model/train'
      fullPath: '/model/train'
      preLoaderRoute: typeof ModelTrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model/evaluate': {
      id: '/model/evaluate'
      path: '/model/evaluate'
      fullPath: '/model/evaluate'
      preLoaderRoute: typeof ModelEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/upload': {
      id: '/data/upload'
      path: '/data/upload'
      fullPath: '/data/upload'
      preLoaderRoute: typeof DataUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/clean': {
      id: '/data/clean'
      path: '/data/clean'
      fullPath: '/data/clean'
      preLoaderRoute: typeof DataCleanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/admin/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PredictRouteChildren {
  PredictBatchRoute: typeof PredictBatchRoute
}

const PredictRouteChildren: PredictRouteChildren = {
  PredictBatchRoute: PredictBatchRoute,
}

const PredictRouteWithChildren =
  PredictRoute._addFileChildren(PredictRouteChildren)

interface StudentsRouteChildren {
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsStudentIdRoute: StudentsStudentIdRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EdaRoute: EdaRoute,
  FeaturesRoute: FeaturesRoute,
  PredictRoute: PredictRouteWithChildren,
  ReportsRoute: ReportsRoute,
  StudentsRoute: StudentsRouteWithChildren,
  AdminModelsRoute: AdminModelsRoute,
  DataCleanRoute: DataCleanRoute,
  DataUploadRoute: DataUploadRoute,
  ModelEvaluateRoute: ModelEvaluateRoute,
  ModelTrainRoute: ModelTrainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
